name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy scikit-learn matplotlib pytest pytest-cov

    - name: Run tests
      run: |
        pytest tests/ -v --tb=short

    - name: Upload coverage report
      if: always()
      run: |
        pytest tests/ --cov=src --cov-report=term-missing
